# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02ea360b45eb799c86f4e1c570db6a6579b71b536962d29182dde8f4c00fde8e3c9056f33251086c3ab25b28aec7ca39187479c7bb32e3fa41313abb703bc7c

test:
  secret_key_base: b664f99a7425cf33d08d0ef6e4f77174d226e5a29b60ebd3e60c9b1fd317ef1ebc798ddce824c9dab816a659ca2bba11e807a2f7f0b0522585163d389cf3c1c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
